trigger:
  branches:
    include:
      - master
      - main
stages:
- stage: build
  jobs:
  - job: Build
  
    pool:
      vmImage: windows-latest
      
    variables:
    - name: CosmosDBConnection
      value: 'AccountEndpoint=https://localhost:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=='
   
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build project'
      inputs:
        projects: '**/*.csproj'
        arguments: '--output publish_output --configuration Release'
    
    - task: DotNetCoreCLI@2
      displayName: 'Publish project'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    
    - task: PowerShell@2
      inputs:
        targetType: inline
        script: >
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"

          Start-CosmosDbEmulator
        failOnStderr: true
        

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*.IntegrationTest.csproj'
        testRunTitle: 'IntegrationTest'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'App'
        publishLocation: 'pipeline'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'Infrastructure'
        artifact: 'Infrastructure'
        publishLocation: 'pipeline'