trigger:
  branches:
    include:
      - master
      - main
stages:
- stage: build
  jobs:
  - job: Build
  
    pool:
      vmImage: windows-latest
      
    variables:
    - name: solution
      value: '**/*.sln'
    - name: buildPlatform
      value: Any CPU
    - name: buildConfiguration
      value: Release
      
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build project'
      inputs:
        projects: '**/*.csproj'
        arguments: '--output publish_output --configuration Release'
    
    - task: DotNetCoreCLI@2
      displayName: 'Publish project'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    
    - task: PowerShell@2
      inputs:
        targetType: inline
        script: >
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"

          Start-CosmosDbEmulator
        failOnStderr: true
        
    - task: PowerShell@2
        inputs:
          targetType: inline
          script: "Write-Host "Starting CosmosDbEmulatorEndpointEnvironmentVariable environment variable update'        
                   Write-Host "Cosmos Host: $($CosmosDbEmulator.Endpoint)"                 
                   Write-Host "CosmosDbEmulatorEndpointEnvironmentVariable is: $($env:CosmosDbEmulatorEndpointEnvironmentVariable)";
                   Write-Host "##vso[task.setvariable variable=CosmosDbEmulatorEndpointEnvironmentVariable]$(CosmosDbEmulator.Endpoint)"
                   Write-Host "Updating CosmosDbEmulatorEndpointEnvironmentVariable is completed"
          failOnStderr: true

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*.UnitTest.csproj'
        testRunTitle: 'Unit Test'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'App'
        publishLocation: 'pipeline'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'Infrastructure'
        artifact: 'Infrastructure'
        publishLocation: 'pipeline'
    
    # Powershell command to start the emulator in VS2019 as the default Cosmos DB emulator task is not compatible in the latest agent pools.

    
    # Powershell command to set the Environment variable in the agent server
    